services:
  redis:
    command: --save 60 1 --loglevel warning
    networks:
      - healthcare_jobs_network
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD-SHELL
        - redis-cli ping | grep PONG
      timeout: 3s
    image: docker.io/library/redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
  app-postgres:
    image: postgres:alpine
    networks:
      - healthcare_jobs_network
    environment:
      POSTGRES_DB: healthcare_jobs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: healthcare_jobs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mailpit:
    image: axllent/mailpit:latest
    networks:
      - healthcare_jobs_network
    ports:
      - "8025:8025"
      - "1025:1025"
  auth-postgres:
    image: postgres:alpine
    networks:
      - healthcare_jobs_network
    environment:
      POSTGRES_DB: sessions_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sessions
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

volumes:
  authentik_db_data:
    driver: local
  redis_data:
    driver: local
  auth_db_data:
    driver: local
  postgres_data:
    driver: local
networks:
  healthcare_jobs_network:
    driver: bridge
