services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: healthcare_jobs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: healthcare_jobs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: